### PR TITLE
Apm improvements

### PR DESCRIPTION
**Pull request by allanchau**
This PR fixes an issue where overriding the exception handler wouldn't work.

## Setup

- [x] Map this into one of your projects.

## Testing

- [x] Trigger an exception and make sure the correct handler is called. The log context should be your own instead of `idearium-lib:common/exception`.

## Notes

- This is a breaking change that requires your local apm file to instantiate the class. `const apm = new Apm();`

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, this one is ready for you to rework.

**Comment by smebberson** [comment]
@allanchau, this is more of a discussion, but do you think it would be better to have the file export a function, that you do the same thing with, rather than a class? So still a breaking change, but just favouring a function rather than a class.

The original design of `idearium-lib` tried to keep to Classes only in the lib folder, and no classes (where possible) in the common folder.

**Comment by allanchau** [comment]
@smebberson Ready for your review again, I'll update the docs in the next PR because the directory structure has changed a bit. I'm thinking of adding a `docs` folder like our other projects.

**Comment by smebberson** [comment]
@allanchau, could you please update the PR with how this is now used?

**Pull request merged**
