### PR TITLE
@idearium/log

### PR DESCRIPTION
**Pull request by allanchau**
This PR is basically a complete rewrite of the library, turning it into a monorepo.

**Testing**

- [x] `cd ./docusaurus/website` and run `yarn start`. Click around the docs to make sure it is working. Note only http://localhost:3000/idearium-lib/docs/log has been populated.
- [x] `cd ./packages/ideearium-log` and run `yarn test`. Make sure the tests pass.
- [x] Create a new `index.js` file in the root directory.
```javascript
'use strict';

const log = require('./packages/idearium-log').init();

log.info({ test: 'another test' }, 'test');
```
- [x] To test remote logging run Run `LOG_REMOTE=true node . | LOG_REMOTE=true INSIGHT_OPS_REGION=eu INSIGHT_OPS_TOKEN=<Insert a token from one of the insight ops logs sets> ./packages/idearium-log/bin/insightops.js`
- [x] To test the same command without remote logging, run Run `LOG_REMOTE=false node . | LOG_REMOTE=false INSIGHT_OPS_REGION=eu INSIGHT_OPS_TOKEN=<Insert a token from one of the insight ops logs sets> ./packages/idearium-log/bin/insightops.js`

**Notes**

- The command to run once this is published should be `node server.js | insightops`.
- Devops has not been setup, each package should automatically be tested when changed. The docs should autopublish on merge to master/tagged commit too.

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson @DinoLeung If you get a spare moment, can you please check this out?
From my testing the logger should be ready to go. If you guys are happy with the structure etc of the project then I can get started on the other modules.

**Comment by smebberson** [comment]
@allanchau, I like where this is heading. Looks good. I love the individual package documentation! I have a few questions though from two perspectives.

## The log package

- Check the image that I got below, it doesn't submit stuff to InsightOps in JSON (which is recommended), [logs here](https://eu.ops.insight.rapid7.com/op/B5FCB0BE81584B8622A4#/search?logs=%5B%221956d417-c129-4e08-bc1b-064fa48f36cf%22%5D&range=Last%2020%20Minutes).
image
- With `LOG_REMOTE=true` there was no logging to the console?

## The mono repo

- With everything moved to _old/_ how can we maintain both versions while we migrate all of the bits and pieces (i.e. and potentially need updates to the old stuff before the migration is complete).
- How will Codefresh work? Can it still do automated released to NPM? Can it support releasing just one package? Can it support releasing multiple packages at a time? Did the note reference below just mean that you haven't done it yet?
> Devops has not been setup, each package should automatically be tested when changed. The docs should autopublish on merge to master/tagged commit too
- I had to run `yarn` from `./docusaurus/website` before `yarn start` would work. Is that intended?
- Would we use GitHub pages to host the documentation website?
- Could we publish the packages in the `@idearium` namespace? `@idearium/log`

**Comment by allanchau** [comment]
@smebberson That's strange, I'll have to look into it. Did you run with a combination of environment variables?

In response to the q's:
- This should probably be treated like a feature branch (create a new feature-* and point this to it). We can still deploy both since they will have different package names.
- Yeah none of the devops stuff has been done. It is missing automated testing and deployment (to NPM and GitHub pages).
- Yeah, I probably missed that step in the setup. I'm not sure if we could add it to the yarn workspace and automate it though?
- Yeah that was the plan, in fact I deployed it when testing out the docs https://idearium.github.io/idearium-lib/
- Yeah that was the plan, I'll have to update it so the packages are named `@idearium/...`

**Comment by smebberson** [comment]
@allanchau, I ran it like `node . | LOG_REMOTE=true INSIGHT_OPS_REGION=eu INSIGHT_OPS_TOKEN=<token> ./packages/idearium-log/bin/insightops.js`

**Comment by smebberson** [comment]
@allanchau, I'm still confused about the strategy behind being able to maintain both versions? Could you please go into more detail about this? I'm confused about a couple of things:

- Because you've moved everything into the old directory, how will the code run?
- Codefresh configuration for this would seem really tricky?

**Comment by allanchau** [comment]
@smebberson Sorry the testing code was wrong, `node .` also requires the environment variables.  I've updated the testing steps with the correct code now. Both commands should get it when running in a project right?

I've removed the old folder now and pointed this to a feature branch. So we will continue with the master branch with how it is now (making sure to update the monorepo as we go). We can publish them seperately because the new packages will be namespaced `@idearium/log` etc

Codefresh has support for monorepos although I haven't added it yet https://codefresh.io/continuous-integration/using-codefresh-with-mono-repos/.

**Comment by smebberson** [comment]
@allanchau, why can't we develop the `packages/<package>` stuff alongside the current `master` setup?

**Comment by allanchau** [comment]
@smebberson Do you mean in the same branch? That would get a bit messy I think.
We would need a bunch of extra logic in the codefresh and codecov files to make it work.

**Comment by smebberson** [comment]
Let me have a read through the Codefresh mono repo thing, I honestly think it's the way we're going to be able to make the most progress. I don't think it's messy either really, because all we're doing is adding a packages folder for the new stuff and a docasaurus folder for documentation of the new stuff. Codecov can be updated to just look at the new stuff, but yeah, it would need to work with codefresh.

**Comment by smebberson** [comment]
@allanchau, the testing steps seem to be incorrect as `./packages/idearium-log/bin/insightops.js` doesn't exist? Also `yarn test` doesn't work in `./packages/idearium-log`.

Can you please go back and check those out and make sure they're inline with the files we have?

**Pull request merged**
